# Generated by Django 3.1.3 on 2020-11-30 23:31

import cloudinary.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('award', '0003_auto_20201201_0203'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='link',
            field=models.CharField(default=django.utils.timezone.now, max_length=70),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='image1',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='projects/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
